[package]
name = "argparse"
version = "2.0.0"
authors = ["Lance Hart <me@lancehart>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/shipsimfan/lib-argparse.git"
license = "GPL-3.0-or-later"
publish = false
